version: "3.9"
services:
  angel-one:
    # image: golang:1.22-ubuntu
    image: golang
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["bash", "-c", "go run ./..."]